version: '3.8'
services:
  youbot_gazebo:
    tty: true
    build:
      context: .
      args:
        http_proxy:
    container_name: youbot_gazebo
    image: fredrikbaberg/youbot-gazebo:local
    network_mode: host
    environment:
      - MASTER_URI
      - DISPLAY
