version: '3.8'
services:
  youbot-gazebo:
    tty: true
    build:
      context: .
      args:
        http_proxy:
    container_name: youbot-gazebo
    image: fredrikbaberg/youbot-gazebo:local
    network_mode: host
    environment:
      - ROS_MASTER_URI
      # - DISPLAY
