version: '3.8'
services:
  roscore:
    container_name: roscore
    image: fredrikbaberg/youbot-jaco-gazebo-rossharp:dev
    network_mode: host
    command: ["roscore"]
  simulation:
    container_name: simulation
    image: fredrikbaberg/youbot-jaco-gazebo-rossharp:dev
    network_mode: host
    command: ["roslaunch", "--wait", "youbot_jaco_gazebo", "youbot_jaco.launch"]
    # command: ["roslaunch", "--wait", "youbot_gazebo_robot", "youbot.launch", "world:=empty_world", "headless:=true"]
  rossharp:
    container_name: rossharp
    image: fredrikbaberg/youbot-jaco-gazebo-rossharp:dev
    network_mode: host
    command: ["roslaunch", "--wait", "file_server", "ros_sharp_communication.launch"]
  rviz:
    container_name: rviz
    image: fredrikbaberg/youbot-jaco-gazebo-rossharp:dev
    network_mode: host
    environment:
      - DISPLAY=host.docker.internal:0.0
    command: ["rosrun", "rviz", "rviz"]
  jaco-home:
    container_name: jaco-home
    image: fredrikbaberg/youbot-jaco-gazebo-rossharp:dev
    network_mode: host
    command: ["rosrun", "kinova_control", "move_robot.py", "j2n6s300"]
