version: '3'
services:
  youbot-jaco-gazebo-rossharp:
    tty: true
    build:
      context: .
      args:
        http_proxy:
    container_name: youbot-jaco-gazebo-rossharp
    image: fredrikbaberg/youbot-jaco-gazebo-rossharp:local
    network_mode: host
    environment:
      - ROS_MASTER_URI
      # - DISPLAY
