version: '3.8'
services:
  youbot_jaco_gazebo:
    tty: true
    build:
      context: .
      args:
        http_proxy:
    container_name: youbot-jaco-gazebo
    image: fredrikbaberg/youbot-jaco-gazebo:local
    network_mode: host
    # environment:
    #   - MASTER_URI='http://localhost:11311'
