version: '3'
services:
  youbot_sim:
    tty: true
    # build: .
    # container_name: youbot_jaco_sim
    # image: youbot-jaco-gazebo
    image: fredrikbaberg/youbot-jaco-gazebo:dev
    network_mode: host
    # environment:
    #   - MASTER_URI='http://localhost:11311'
