version: '3'
services:
  rossharp:
    tty: true
    # build: .
    # container_name: rossharp
    # image: rossharp
    image: fredrikbaberg/rossharp:dev
    network_mode: host
    # environment:
    #   - MASTER_URI='http://localhost:11311'
