version: '3.8'
services:
  rossharp:
    tty: true
    build:
      context: .
      args:
        http_proxy:
    container_name: rossharp
    image: fredrikbaberg/rossharp:local
    network_mode: host
    environment:
      - ROS_MASTER_URI
